name: "Build and deploy to GitHub Pages"

on:
  push:
    branches: "main"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - run: |
        git log --pretty=format:"%h %ci %an %s" -n 1 -- site/
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: tscholak
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build -L
    - run: nix run .# -- -f config.json
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build
        path: ./build
    - uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        repo: tscholak/tscholak.github.io
        target_branch: main
        build_dir: ./build
        keep_history: false
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
