name: "Build and deploy to GitHub Pages"

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git log --pretty=format:"%h %ci %an %s" -n 1 -- site/
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v10
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv test
      - run: devenv shell devenv-generate-build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  deploy:
    name: "Deploy"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          repo: tscholak/tscholak.github.io
          target_branch: main
          build_dir: ./build
          keep_history: false
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
